# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd93c19653bb6b7902307f82be19f0e31ecb2e41a47d0d22a456dab27c01193d9990d7c828d758c114492c532a341d81a4f20404e771ddc14fa7258b70b5629b

test:
  secret_key_base: a947d9c2d72e480ae3d1cd9156ce35b193d60e568bbe056b527cd0263cdf90a9dd40bb9474ced89b59bcdd72140b3cc8ed3667764e73184665857350b0c13c2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
